export class MedicalScreening {
  areYouHealthy;
  doesYourFamilyAgreeForyouToDonate;
  doesYourAnkleSwellEdnOfDay;
  areYouAHighRiskForhepatitisOrHiv;
  whatsYourWeight;
  whatsYourHeight;
  AreYouARegularBloodDonor;
  DoYouGetUpMorethanOnceAtNight;
  haveYouEverBeenTestedForHiv;
  AreYouOrYourPartnerRiskOfSTI;
  areYouAPlateletDonor;
  areYouWillingToBeAproachedToBeAPlatelet;
  IConsentToMyPersonalInfoGiveToSANBS;
  IAgreeToBiengContactedBySANBSAndWPBTSToDonatePlatelet;
  HaveYouEverBeenPregnant;
  IfSoNumberOfPregnancies;
  dateOfLastPregnancy;
  areYouWillingToBeApproachedToBeAPlateletDonor;
  iConsentToMyPersonalInformationBeingGivenSABSandWPBTS;
  iAgreeToBeContactedBySANBSandWPBTSToDonatePlatelets;
  haveYouEverBeenPregnant;
}
