/**
 * Blue Frameworks
 * Spring Framework 5
 *
 * OpenAPI spec version: 1.0
 * Contact: luke.petzer@younglings.africa
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Timestamp } from './timestamp';


export interface OnlineRegistrationDTO {
    accPeriod?: string;
    address1?: string;
    address2?: string;
    address3?: string;
    birthDate?: string;
    commsInd?: number;
    countryCode?: string;
    /**
     * /api/v1/countrycodes for values(1-252).
     */
    countryCodeId?: number;
    countryId?: number;
    createOpr?: string;
    createdDate?: Timestamp;
    editDate?: Timestamp;
    editOpr?: string;
    email?: string;
    ethnicGroupId?: number;
    firstContactEmail?: string;
    firstContactMobile?: string;
    firstContactName?: string;
    firstContactRelationship?: number;
    firstName?: string;
    gender?: number;
    hashSearch?: string;
    hlaConfirm?: number;
    homePhone?: string;
    id?: number;
    idNumber?: string;
    idType?: number;
    mobile?: string;
    newsLetter?: number;
    p1?: number;
    p10?: number;
    p2?: number;
    p3?: number;
    p4?: number;
    p5?: string;
    p6?: number;
    p7?: number;
    p8?: number;
    p9?: number;
    postalCode?: string;
    provinceId?: number;
    q11?: number;
    q110?: number;
    q111a?: number;
    q111b?: number;
    q111c?: number;
    q111d?: number;
    q112a?: number;
    q112b?: number;
    q112c?: string;
    q12?: number;
    q13?: number;
    q14?: number;
    q15?: string;
    q16?: string;
    q17?: number;
    q18?: number;
    q19?: number;
    q21?: number;
    q210?: number;
    q210a?: string;
    q211?: number;
    q211a?: string;
    q212?: number;
    q212a?: string;
    q213?: number;
    q213a?: string;
    q214?: number;
    q214a?: string;
    q215?: number;
    q215a?: string;
    q21a?: string;
    q21b?: string;
    q22?: number;
    q22a?: string;
    q23?: number;
    q23a?: string;
    q24?: number;
    q25?: number;
    q25a?: string;
    q26?: number;
    q26a?: string;
    q26b?: string;
    q27?: number;
    q27a?: string;
    q28?: number;
    q28a?: string;
    q29?: number;
    q29a?: string;
    recruitmentInd?: number;
    refNo?: string;
    regType?: string;
    regTypeId?: number;
    region?: string;
    result?: string;
    secondContactEmail?: string;
    secondContactMobile?: string;
    secondContactName?: string;
    secondContactRelationship?: number;
    sffStaff?: number;
    status?: number;
    stemCellConfirm?: number;
    surname?: string;
    sysField?: number;
    titleId?: number;
    vettedRegistrationNo?: string;
    webVisible?: number;
    workPhone?: string;
}
